### ISSUE TITLE
add BluePrints to ItemList.hpp

### ISSUE THREAD

**Issue by SlikerDev** [SoTMaulder/SoTMaulder-Palworld#1]
const auto blueprint =
{
 "Blueprint_ClothArmorHeat_2",
 "Blueprint_ClothArmorHeat_3",
 "Blueprint_ClothArmorHeat_4",
 "Blueprint_ClothArmorHeat_5",
 "Blueprint_ClothArmorCold_2",
 "Blueprint_ClothArmorCold_3",
 "Blueprint_ClothArmorCold_4",
 "Blueprint_ClothArmorCold_5",
 "Blueprint_FurArmorHeat_2",
 "Blueprint_FurArmorHeat_3",
 "Blueprint_FurArmorHeat_4",
 "Blueprint_FurArmorHeat_5",
 "Blueprint_FurArmorCold_2",
 "Blueprint_FurArmorCold_3",
 "Blueprint_FurArmorCold_4",
 "Blueprint_FurArmorCold_5",
 "Blueprint_CopperArmorHeat_2",
 "Blueprint_CopperArmorHeat_3",
 "Blueprint_CopperArmorHeat_4",
 "Blueprint_CopperArmorHeat_5",
 "Blueprint_CopperArmorCold_2",
 "Blueprint_CopperArmorCold_3",
 "Blueprint_CopperArmorCold_4",
 "Blueprint_CopperArmorCold_5",
 "Blueprint_IronArmorHeat_2",
 "Blueprint_IronArmorHeat_3",
 "Blueprint_IronArmorHeat_4",
 "Blueprint_IronArmorHeat_5",
 "Blueprint_IronArmorCold_2",
 "Blueprint_IronArmorCold_3",
 "Blueprint_IronArmorCold_4",
 "Blueprint_IronArmorCold_5",
 "Blueprint_StealArmorHeat_2",
 "Blueprint_StealArmorHeat_3",
 "Blueprint_StealArmorHeat_4",
 "Blueprint_StealArmorHeat_5",
 "Blueprint_StealArmorCold_2",
 "Blueprint_StealArmorCold_3",
 "Blueprint_StealArmorCold_4",
 "Blueprint_StealArmorCold_5",
 "Blueprint_FurHelmet_2",
 "Blueprint_FurHelmet_3",
 "Blueprint_FurHelmet_4",
 "Blueprint_FurHelmet_5",
 "Blueprint_CopperHelmet_2",
 "Blueprint_CopperHelmet_3",
 "Blueprint_CopperHelmet_4",
 "Blueprint_CopperHelmet_5",
 "Blueprint_IronHelmet_2",
 "Blueprint_IronHelmet_3",
 "Blueprint_IronHelmet_4",
 "Blueprint_IronHelmet_5",
 "Blueprint_StealHelmet_2",
 "Blueprint_StealHelmet_3",
 "Blueprint_StealHelmet_4",
 "Blueprint_StealHelmet_5",
 "Blueprint_Head001_1",
 "Blueprint_Head001_2",
 "Blueprint_Head001_3",
 "Blueprint_Head001_4",
 "Blueprint_Head001_5",
 "Blueprint_Head002_1",
 "Blueprint_Head002_2",
 "Blueprint_Head002_3",
 "Blueprint_Head002_4",
 "Blueprint_Head003_1",
 "Blueprint_Head003_2",
 "Blueprint_Head003_3",
 "Blueprint_Head003_4",
 "Blueprint_Head003_5",
 "Blueprint_Head004_1",
 "Blueprint_Head004_2",
 "Blueprint_Head004_3",
 "Blueprint_Head004_4",
 "Blueprint_Head004_5",
 "Blueprint_Head005_1",
 "Blueprint_Head005_2",
 "Blueprint_Head005_3",
 "Blueprint_Head005_4",
 "Blueprint_Head005_5",
 "Blueprint_Head006_1",
 "Blueprint_Head006_2",
 "Blueprint_Head006_3",
 "Blueprint_Head006_4",
 "Blueprint_Head006_5",
 "Blueprint_Head007_1",
 "Blueprint_Head007_2",
 "Blueprint_Head007_3",
 "Blueprint_Head007_4",
 "Blueprint_Head007_5",
 "Blueprint_Head008_1",
 "Blueprint_Head008_2",
 "Blueprint_Head008_3",
 "Blueprint_Head008_4",
 "Blueprint_Head008_5",
 "Blueprint_Head009_1",
 "Blueprint_Head009_2",
 "Blueprint_Head009_3",
 "Blueprint_Head009_4",
 "Blueprint_Head009_5",
 "Blueprint_Head010_1",
 "Blueprint_Head010_2",
 "Blueprint_Head010_3",
 "Blueprint_Head010_4",
 "Blueprint_Head010_5",
 "Blueprint_Head011_1",
 "Blueprint_Head011_2",
 "Blueprint_Head011_3",
 "Blueprint_Head011_4",
 "Blueprint_Head011_5",
 "Blueprint_Head012_1",
 "Blueprint_Head012_2",
 "Blueprint_Head012_3",
 "Blueprint_Head012_4",
 "Blueprint_Head012_5",
 "Blueprint_Head013_1",
 "Blueprint_Head013_2",
 "Blueprint_Head013_3",
 "Blueprint_Head013_4",
 "Blueprint_Head013_5",
 "Blueprint_Head014_1",
 "Blueprint_Head014_2",
 "Blueprint_Head014_3",
 "Blueprint_Head014_4",
 "Blueprint_Head014_5",
 "Blueprint_Head015_1",
 "Blueprint_Head015_2",
 "Blueprint_Head015_3",
 "Blueprint_Head015_4",
 "Blueprint_Head015_5",
 "Blueprint_Head016_1",
 "Blueprint_Head016_2",
 "Blueprint_Head016_3",
 "Blueprint_Head016_4",
 "Blueprint_Head016_5",
 "Blueprint_Head017_1",
 "Blueprint_Head017_2",
 "Blueprint_Head017_3",
 "Blueprint_Head017_4",
 "Blueprint_Head017_5",
 "Blueprint_WeakerBow_2",
 "Blueprint_WeakerBow_3",
 "Blueprint_WeakerBow_4",
 "Blueprint_WeakerBow_5",
 "Blueprint_BowGun_2",
 "Blueprint_BowGun_3",
 "Blueprint_BowGun_4",
 "Blueprint_BowGun_5",
 "Blueprint_AssaultRifle_Default2",
 "Blueprint_AssaultRifle_Default3",
 "Blueprint_AssaultRifle_Default4",
 "Blueprint_AssaultRifle_Default5",
 "Blueprint_PumpActionShotgun_2",
 "Blueprint_PumpActionShotgun_3",
 "Blueprint_PumpActionShotgun_4",
 "Blueprint_PumpActionShotgun_5",
 "Blueprint_HandGun_Default_2",
 "Blueprint_HandGun_Default_3",
 "Blueprint_HandGun_Default_4",
 "Blueprint_HandGun_Default_5",
 "Blueprint_Launcher_Default_2",
 "Blueprint_Launcher_Default_3",
 "Blueprint_Launcher_Default_4",
 "Blueprint_Launcher_Default_5",
 "Blueprint_ClothArmor_2",
 "Blueprint_ClothArmor_3",
 "Blueprint_ClothArmor_4",
 "Blueprint_ClothArmor_5",
 "Blueprint_FurArmor_2",
 "Blueprint_FurArmor_3",
 "Blueprint_FurArmor_4",
 "Blueprint_FurArmor_5",
 "Blueprint_CopperArmor_2",
 "Blueprint_CopperArmor_3",
 "Blueprint_CopperArmor_4",
 "Blueprint_CopperArmor_5",
 "Blueprint_IronArmor_2",
 "Blueprint_IronArmor_3",
 "Blueprint_IronArmor_4",
 "Blueprint_IronArmor_5",
 "Blueprint_StealArmor_2",
 "Blueprint_StealArmor_3",
 "Blueprint_StealArmor_4",
 "Blueprint_StealArmor_5",
};

**Comment by SoTMaulder** [comment]
> const auto blueprint = { "Blueprint_ClothArmorHeat_2", "Blueprint_ClothArmorHeat_3", "Blueprint_ClothArmorHeat_4", "Blueprint_ClothArmorHeat_5", "Blueprint_ClothArmorCold_2", "Blueprint_ClothArmorCold_3", "Blueprint_ClothArmorCold_4", "Blueprint_ClothArmorCold_5", "Blueprint_FurArmorHeat_2", "Blueprint_FurArmorHeat_3", "Blueprint_FurArmorHeat_4", "Blueprint_FurArmorHeat_5", "Blueprint_FurArmorCold_2", "Blueprint_FurArmorCold_3", "Blueprint_FurArmorCold_4", "Blueprint_FurArmorCold_5", "Blueprint_CopperArmorHeat_2", "Blueprint_CopperArmorHeat_3", "Blueprint_CopperArmorHeat_4", "Blueprint_CopperArmorHeat_5", "Blueprint_CopperArmorCold_2", "Blueprint_CopperArmorCold_3", "Blueprint_CopperArmorCold_4", "Blueprint_CopperArmorCold_5", "Blueprint_IronArmorHeat_2", "Blueprint_IronArmorHeat_3", "Blueprint_IronArmorHeat_4", "Blueprint_IronArmorHeat_5", "Blueprint_IronArmorCold_2", "Blueprint_IronArmorCold_3", "Blueprint_IronArmorCold_4", "Blueprint_IronArmorCold_5", "Blueprint_StealArmorHeat_2", "Blueprint_StealArmorHeat_3", "Blueprint_StealArmorHeat_4", "Blueprint_StealArmorHeat_5", "Blueprint_StealArmorCold_2", "Blueprint_StealArmorCold_3", "Blueprint_StealArmorCold_4", "Blueprint_StealArmorCold_5", "Blueprint_FurHelmet_2", "Blueprint_FurHelmet_3", "Blueprint_FurHelmet_4", "Blueprint_FurHelmet_5", "Blueprint_CopperHelmet_2", "Blueprint_CopperHelmet_3", "Blueprint_CopperHelmet_4", "Blueprint_CopperHelmet_5", "Blueprint_IronHelmet_2", "Blueprint_IronHelmet_3", "Blueprint_IronHelmet_4", "Blueprint_IronHelmet_5", "Blueprint_StealHelmet_2", "Blueprint_StealHelmet_3", "Blueprint_StealHelmet_4", "Blueprint_StealHelmet_5", "Blueprint_Head001_1", "Blueprint_Head001_2", "Blueprint_Head001_3", "Blueprint_Head001_4", "Blueprint_Head001_5", "Blueprint_Head002_1", "Blueprint_Head002_2", "Blueprint_Head002_3", "Blueprint_Head002_4", "Blueprint_Head003_1", "Blueprint_Head003_2", "Blueprint_Head003_3", "Blueprint_Head003_4", "Blueprint_Head003_5", "Blueprint_Head004_1", "Blueprint_Head004_2", "Blueprint_Head004_3", "Blueprint_Head004_4", "Blueprint_Head004_5", "Blueprint_Head005_1", "Blueprint_Head005_2", "Blueprint_Head005_3", "Blueprint_Head005_4", "Blueprint_Head005_5", "Blueprint_Head006_1", "Blueprint_Head006_2", "Blueprint_Head006_3", "Blueprint_Head006_4", "Blueprint_Head006_5", "Blueprint_Head007_1", "Blueprint_Head007_2", "Blueprint_Head007_3", "Blueprint_Head007_4", "Blueprint_Head007_5", "Blueprint_Head008_1", "Blueprint_Head008_2", "Blueprint_Head008_3", "Blueprint_Head008_4", "Blueprint_Head008_5", "Blueprint_Head009_1", "Blueprint_Head009_2", "Blueprint_Head009_3", "Blueprint_Head009_4", "Blueprint_Head009_5", "Blueprint_Head010_1", "Blueprint_Head010_2", "Blueprint_Head010_3", "Blueprint_Head010_4", "Blueprint_Head010_5", "Blueprint_Head011_1", "Blueprint_Head011_2", "Blueprint_Head011_3", "Blueprint_Head011_4", "Blueprint_Head011_5", "Blueprint_Head012_1", "Blueprint_Head012_2", "Blueprint_Head012_3", "Blueprint_Head012_4", "Blueprint_Head012_5", "Blueprint_Head013_1", "Blueprint_Head013_2", "Blueprint_Head013_3", "Blueprint_Head013_4", "Blueprint_Head013_5", "Blueprint_Head014_1", "Blueprint_Head014_2", "Blueprint_Head014_3", "Blueprint_Head014_4", "Blueprint_Head014_5", "Blueprint_Head015_1", "Blueprint_Head015_2", "Blueprint_Head015_3", "Blueprint_Head015_4", "Blueprint_Head015_5", "Blueprint_Head016_1", "Blueprint_Head016_2", "Blueprint_Head016_3", "Blueprint_Head016_4", "Blueprint_Head016_5", "Blueprint_Head017_1", "Blueprint_Head017_2", "Blueprint_Head017_3", "Blueprint_Head017_4", "Blueprint_Head017_5", "Blueprint_WeakerBow_2", "Blueprint_WeakerBow_3", "Blueprint_WeakerBow_4", "Blueprint_WeakerBow_5", "Blueprint_BowGun_2", "Blueprint_BowGun_3", "Blueprint_BowGun_4", "Blueprint_BowGun_5", "Blueprint_AssaultRifle_Default2", "Blueprint_AssaultRifle_Default3", "Blueprint_AssaultRifle_Default4", "Blueprint_AssaultRifle_Default5", "Blueprint_PumpActionShotgun_2", "Blueprint_PumpActionShotgun_3", "Blueprint_PumpActionShotgun_4", "Blueprint_PumpActionShotgun_5", "Blueprint_HandGun_Default_2", "Blueprint_HandGun_Default_3", "Blueprint_HandGun_Default_4", "Blueprint_HandGun_Default_5", "Blueprint_Launcher_Default_2", "Blueprint_Launcher_Default_3", "Blueprint_Launcher_Default_4", "Blueprint_Launcher_Default_5", "Blueprint_ClothArmor_2", "Blueprint_ClothArmor_3", "Blueprint_ClothArmor_4", "Blueprint_ClothArmor_5", "Blueprint_FurArmor_2", "Blueprint_FurArmor_3", "Blueprint_FurArmor_4", "Blueprint_FurArmor_5", "Blueprint_CopperArmor_2", "Blueprint_CopperArmor_3", "Blueprint_CopperArmor_4", "Blueprint_CopperArmor_5", "Blueprint_IronArmor_2", "Blueprint_IronArmor_3", "Blueprint_IronArmor_4", "Blueprint_IronArmor_5", "Blueprint_StealArmor_2", "Blueprint_StealArmor_3", "Blueprint_StealArmor_4", "Blueprint_StealArmor_5", };

Added everything except the random helmets, only did the primary ones. I werent gonna sit there and rename all the other ones i dont even know what they are lol
