### ISSUE TITLE
about spawning pals

### ISSUE THREAD

**Issue by a66a66a** [SoTMaulder/SoTMaulder-Palworld#15]
please tell me why I don't see the option for spawning pals
my English is not good, maybe I missed it
i hope you can give me pictures and tell me how to use it

**Comment by a66a66a** [comment]
the comment from 5 days ago seems to say that this feature has been deleted.

**Comment by Cyk-Fad** [comment]
> the comment from 5 days ago seems to say that this feature has been deleted.

可以用

**Comment by a66a66a** [comment]
> > 5 天前的評論似乎說此功能已被刪除。
> 
> 可以用

怎麼搞兄弟

**Comment by Cyk-Fad** [comment]
> > > 5 天前的評論似乎說此功能已被刪除。
> > 
> > 
> > 可以用
> 
> 怎麼搞兄弟

加一个联系方式

**Comment by a66a66a** [comment]
> > > > 5 天前的評論似乎說此功能已被刪除。
> > > 
> > > 
> > > 可以用
> > 
> > 
> > 怎麼搞兄弟
> 
> 加一个联系方式

+q:1279152461

**Comment by a66a66a** [comment]
> > > > > 5 天前的評論似乎說此功能已被刪除。
> > > > 
> > > > 
> > > > 可以用
> > > 
> > > 
> > > 怎麼搞兄弟
> > 
> > 
> > 加一个联系方式
> 
> +q:1279152461

或是+v也可以
