### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by ColoGlaze** [SoTMaulder/SoTMaulder-Palworld#16]
Hello, I have successfully compiled a DLL file in Visual Studio2022, but when I inject it into the game, the injector shows successful injection, but there is no response in the game. How should I use this compiled DLL file？

**Comment by AT7921** [comment]
把编译好的dll发给我我教你

**Comment by ColoGlaze** [comment]
Okay, I already have a compiled DLL file. How can I contact you via email? Telegram? Discord? Or what other contact information?
