### ISSUE TITLE
Unable to activate it

### ISSUE THREAD

**Issue by farsdewibs0n** [SoTMaulder/SoTMaulder-Palworld#21]
Am I missing something VS 2022 (it does compile, so there shouldnt be any issue)? Or is there specialized injector exist for this game?

**Comment by Bjorn-Visser** [comment]
use process hacker for instance, run it as admin (elevated)
Then find your service (Pal) and than right click the process => misc => inject dll
After compiling the sln you'd find the dll in the bin folder

**Comment by farsdewibs0n** [comment]
> use process hacker for instance, run it as admin (elevated) Then find your service (Pal) and than right click the process => misc => inject dll After compiling the sln you'd find the dll in the bin folder

Tried it. but when pressin INSERT, the menu doesnt show up

**Comment by SoTMaulder** [comment]
> > use process hacker for instance, run it as admin (elevated) Then find your service (Pal) and than right click the process => misc => inject dll After compiling the sln you'd find the dll in the bin folder
> 
> Tried it. but when pressin INSERT, the menu doesnt show up

u on xbox/steam, what game version (lower right corner in game)

**Comment by farsdewibs0n** [comment]
> > > use process hacker for instance, run it as admin (elevated) Then find your service (Pal) and than right click the process => misc => inject dll After compiling the sln you'd find the dll in the bin folder
> > 
> > 
> > Tried it. but when pressin INSERT, the menu doesnt show up
> 
> u on xbox/steam, what game version (lower right corner in game)

1.4.1 Steam version
