### ISSUE TITLE
Too bad

### ISSUE THREAD

**Issue by blitzmichael2** [SoTMaulder/SoTMaulder-Palworld#25]
Too bad, the open source people got greedy, now they want it to keep it amongst themselves.

**Comment by SoTMaulder** [comment]
> Too bad, the open source people got greedy, now they want it to keep it amongst themselves.

lol i pretty much quit the game, if someone wants to update it ill pull request, but im not putting any more effort to it

**Comment by blitzmichael2** [comment]
> etty much quit the game, if someone wants to update it ill pull request, but im not putting any more effort to it

thanks, that is all the closure I need from you.
