### ISSUE TITLE
[Not an issue] What is Pal Condensation ? 

### ISSUE THREAD

**Issue by Mangaia** [SoTMaulder/SoTMaulder-Palworld#4]
Hi,

I just do not understand what that does .

![image](https://github.com/SoTMaulder/SoTMaulder-Palworld/assets/21020827/bd271ad4-5cb8-4076-a094-e5cc0fcc2356)

Could you please give me an explanation? Thanks!

**Comment by Ruethy** [comment]
Theres a thing you can build in game, from what i gathered it lowers the count from 4 to 1. So you would put 1 pal in and like 3/4 others you would sacrifice to make the 1 pal more powerful. With the mod turned on it brings the amount down to only 1 pal.

(Im not affiliated with this mod i am just a person who enjoys freedom)
