### ISSUE TITLE
Unlocking the whole map function no longer works

### ISSUE THREAD

**Issue by Lucifer745** [SoTMaulder/SoTMaulder-Palworld#6]
Unlocking the whole map function no longer works

**Comment by SoTMaulder** [comment]
Use it, then relog, or use it at main menu then join.

**Comment by Mangaia** [comment]
> > 使用它，然后重新登录，或在主菜单中使用它，然后加入。
> 
> It doesn't work whether you use it in the main menu or log out and log in again after using it. ![8](https://private-user-images.githubusercontent.com/32611894/301847566-20917a87-ea08-4be5-b8c3-089d252af2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDM5MzksIm5iZiI6MTcwNzAwMzYzOSwicGF0aCI6Ii8zMjYxMTg5NC8zMDE4NDc1NjYtMjA5MTdhODctZWEwOC00YmU1LWI4YzMtMDg5ZDI1MmFmMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjVkMjA0YzM0YWIyNjJiZjNhMGI1YzUxMDNhZmZlZjVjYmRiZDU2ZTk0MDMxMDUwNzBhN2M2MmJlYjZhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.063bIQgCvFh7KEmq2MONzKnDkLAziC_4-LteWFoWat8)

Yep same for me.

**Comment by SoTMaulder** [comment]
> > > 使用它，然后重新登录，或在主菜单中使用它，然后加入。
> > 
> > 
> > It doesn't work whether you use it in the main menu or log out and log in again after using it. ![8](https://private-user-images.githubusercontent.com/32611894/301847566-20917a87-ea08-4be5-b8c3-089d252af2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDM5MzksIm5iZiI6MTcwNzAwMzYzOSwicGF0aCI6Ii8zMjYxMTg5NC8zMDE4NDc1NjYtMjA5MTdhODctZWEwOC00YmU1LWI4YzMtMDg5ZDI1MmFmMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjVkMjA0YzM0YWIyNjJiZjNhMGI1YzUxMDNhZmZlZjVjYmRiZDU2ZTk0MDMxMDUwNzBhN2M2MmJlYjZhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.063bIQgCvFh7KEmq2MONzKnDkLAziC_4-LteWFoWat8)
> 
> Yep same for me. sorry for late reply, yah ill have to look into it, ive been busy with tarkov, but will come back to this asap to hopefully get it working again

**Comment by Lucifer745** [comment]
> > > > 使用它，然后重新登录，或在主菜单中使用它，然后加入。
> > > 
> > > 
> > > 无论是在主菜单中使用还是使用后注销并重新登录都不起作用。[![8](https://private-user-images.githubusercontent.com/32611894/301847566-20917a87-ea08-4be5-b8c3-089d252af2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDM5MzksIm5iZiI6MTcwNzAwMzYzOSwicGF0aCI6Ii8zMjYxMTg5NC8zMDE4NDc1NjYtMjA5MTdhODctZWEwOC00YmU1LWI4YzMtMDg5ZDI1MmFmMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjVkMjA0YzM0YWIyNjJiZjNhMGI1YzUxMDNhZmZlZjVjYmRiZDU2ZTk0MDMxMDUwNzBhN2M2MmJlYjZhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.063bIQgCvFh7KEmq2MONzKnDkLAziC_4-LteWFoWat8)](javascript:void(0))
> > 
> > 
> > 是的，对我来说也一样。很抱歉回复晚了，是的，我必须调查一下，我一直忙于塔科夫，但会尽快回到这个问题，希望让它再次工作

Haha, now I suspect this issue has been officially fixed, but the obelisks are still unlockable throughout the map, they just don't show up on the map for the time being. You will only find the obelisk if you unlock the area near it. in unlocked state

> > > > 使用它，然后重新登录，或在主菜单中使用它，然后加入。
> > > 
> > > 
> > > It doesn't work whether you use it in the main menu or log out and log in again after using it. [![8](https://private-user-images.githubusercontent.com/32611894/301847566-20917a87-ea08-4be5-b8c3-089d252af2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDM5MzksIm5iZiI6MTcwNzAwMzYzOSwicGF0aCI6Ii8zMjYxMTg5NC8zMDE4NDc1NjYtMjA5MTdhODctZWEwOC00YmU1LWI4YzMtMDg5ZDI1MmFmMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjVkMjA0YzM0YWIyNjJiZjNhMGI1YzUxMDNhZmZlZjVjYmRiZDU2ZTk0MDMxMDUwNzBhN2M2MmJlYjZhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.063bIQgCvFh7KEmq2MONzKnDkLAziC_4-LteWFoWat8)](javascript:void(0))
> > 
> > 
> > Yep same for me. sorry for late reply, yah ill have to look into it, ive been busy with tarkov, but will come back to this asap to hopefully get it working again

Haha, now I suspect this issue has been officially fixed, but the obelisks are still unlockable throughout the map, they just don't show up on the map for the time being. You will only find the obelisk if you unlock the area near it. in unlocked state

**Comment by Lucifer745** [comment]
> > > > 使用它，然后重新登录，或在主菜单中使用它，然后加入。
> > > 
> > > 
> > > It doesn't work whether you use it in the main menu or log out and log in again after using it. [![8](https://private-user-images.githubusercontent.com/32611894/301847566-20917a87-ea08-4be5-b8c3-089d252af2e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMDM5MzksIm5iZiI6MTcwNzAwMzYzOSwicGF0aCI6Ii8zMjYxMTg5NC8zMDE4NDc1NjYtMjA5MTdhODctZWEwOC00YmU1LWI4YzMtMDg5ZDI1MmFmMmUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDIzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYjVkMjA0YzM0YWIyNjJiZjNhMGI1YzUxMDNhZmZlZjVjYmRiZDU2ZTk0MDMxMDUwNzBhN2M2MmJlYjZhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.063bIQgCvFh7KEmq2MONzKnDkLAziC_4-LteWFoWat8)](javascript:void(0))
> > 
> > 
> > Yep same for me. sorry for late reply, yah ill have to look into it, ive been busy with tarkov, but will come back to this asap to hopefully get it working again

Haha, now I suspect this issue has been officially fixed, but the obelisks are still unlockable throughout the map, they just don't show up on the map for the time being. You will only find the obelisk if you unlock the area near it. in unlocked state
