### ISSUE TITLE
Hello, I would like to ask how I can use this source code and generate dll. I am a novice. Thank you.

### ISSUE THREAD

**Issue by hjz1294350473** [SoTMaulder/SoTMaulder-Palworld#7]
Hello, I would like to ask how I can use this source code and generate dll. I am a novice. Thank you.

**Comment by SoTMaulder** [comment]
www.google.com

**Comment by hjz1294350473** [comment]
Sorry, I didn't understand

**Comment by bnthomason** [comment]
So, you need visual studio 2019 with build tools v143. There are some resources on google to help you figure the tool redirect out.

https://learn.microsoft.com/en-us/answers/questions/769911/visual-studio-2019-build-tools-v143
https://stackoverflow.com/questions/72573273/the-build-tools-for-v143-cannot-be-found-build-tool-installed-using-correct
^^^

Try learning here, then compile
